### ISSUE TITLE
Flock compatibility

### ISSUE THREAD

**Issue by evert** [fruux/Baikal2#35]
_From @pguth on September 21, 2014 15:54_

It seems that Baikal does not fully comply with WebDAV collection properties and thus is not compatible with Flock (see [Unable to login to Baikal #22](https://github.com/WhisperSystems/Flock/issues/22#issuecomment-56113879)).

Are there plans to fix that?

_Copied from original issue: fruux/Baikal#281_

**Comment by evert** [comment]
_From @x3ro on October 22, 2014 16:56_

:+1:

**Comment by evert** [comment]
_From @netgusto on November 3, 2014 21:18_

As @evert points it out here https://github.com/WhisperSystems/Flock/issues/19#issuecomment-56572029:

* sabre/dav 2.x is required
* http://sabre.io/dav/property-storage has to be enabled in Baïkal DAV services

We will do this in branch2.

**Comment by evert** [comment]
_From @naevtamarkus on November 21, 2014 9:53_

+1!

**Comment by evert** [comment]
_From @patcon on November 23, 2014 22:57_

+1

**Comment by evert** [comment]
_From @jaromil on May 22, 2015 11:12_

+1

Did not know about this software, but I'd start using Baikal tomorrow if sabre/dav 2.x support would be there for the property storage (and Flock) to work

**Comment by evert** [comment]
_From @patcon on May 22, 2015 14:38_

fwiw, this works with flock, if you're not partial to baikal (I couldn't get flock working with baikal either, so went this route):
http://github.com/patcon/flock-webdav-vagrant
https://github.com/patcon/chef-darwin-calendar-server

**Comment by evert** [comment]
_From @jaromil on June 3, 2015 7:40_

thanks a lot! I'm not partial to anything, just looking for something that works and nothing else really does atm.

**Comment by patcon** [comment]
I think this could be shut down or retitled, as Flock has discontinued, largely due to the experiences of working with webdav: https://gist.github.com/rhodey/873ae9d527d8d2a38213

**Comment by evert** [comment]
Fair enough! Makes sense to close this then.
