### ISSUE TITLE
HTTPS project website / signing .zip bundles of baikal releases

### ISSUE THREAD

**Issue by evert** [fruux/Baikal2#42]
_From @sudoman on October 14, 2013 19:13_

it would be nice if https:// worked for baikal-server.com, to offer some verification of file downloads.

self-bundling through git offers the https:// support of github.com, but it seems to require at least a couple of dependencies outside of debian repos, including one outside of pip.

there's also gpg-sigs which would be cool. :-)

_Copied from original issue: fruux/Baikal#135_

**Comment by evert** [comment]
_From @netgusto on November 26, 2014 9:25_

Yes, https:// on baikal-server.com is a good idea. Have not done it yet because certificates cost money :)

Do you know any certificate authority that provide ssl certificates for open-source projects ?

**Comment by evert** [comment]
_From @jpcaruana on November 26, 2014 13:35_

https://www.globalsign.com/ssl/ssl-open-source/
https://fr.godaddy.com/ssl/ssl-open-source.aspx

**Comment by evert** [comment]
GPG is free

**Comment by evert** [comment]
_From @shoeper on January 3, 2015 21:7_

Startssl offers free certificates (domain validated, valid for one month) and cheap ones ($60 for 350 days - you can create as much certificates as you want, all valid for two years afaik).
As an alternative you could host baikal on bitbucket.

**Comment by evert** [comment]
_From @m0yellow on January 7, 2016 10:4_

StartSSL (startssl.com) has free certificate for one year! (there is nothing signed then the e-mail validated domain, but this is still a huge step forward). It has been like that for years, and worked well with different browsers and and Use-Cases (I use it for IMAP/SMTP/HTTPS for my webmail).
CACert and Let's Encrypt are also free, and give you an informed choice, if you want longer but not broadly supported certificates (can still be validated if you really want to), or running a script to prolong the certificate all three months.

I migrated all my symfony projectsl to https in a virtual hosting environment, and I never regret that.

**Comment by sudoman** [comment]
I hear good things about [Let's Encrypt](https://letsencrypt.org).

**Comment by evert** [comment]
This was marked as a baikal2 bug, so we moved it to the baikal2 repo... but really this applies to baikal1 as well.. so I'm going to be super annoying, close this ticket and reopen the original :/
