### ISSUE TITLE
baikal2 on windows iis possible??

### ISSUE THREAD

**Issue by GoriBoy** [fruux/Baikal2#46]
Hello,
i want to contribute with $$ and to ask if baikal2 will be workz under iis like baikal1.
can i share calendars with this new version?

**Comment by evert** [comment]
Most of our development is not focussed on baikal 1, not 2.

**Comment by MarkMaldaba** [comment]
> development is not focussed on baikal 1, not 2
@evert - Bit confusing, that sentence!  Which is it?

**Comment by evert** [comment]
Oops... its "1, not 2". I

**Comment by MarkMaldaba** [comment]
Really?  So is Baikal 2 abandoned?  Which version will calendar sharing be added to (once sabre/dav supports it)?

**Comment by evert** [comment]
I don't know.
